- README.md
- package-lock.json
- package.json
- src/get-search-params.ts
> Implement get-search-params

- README.md
- package-lock.json
- package.json
- src/create-server-context.tsx
- src/get-server-context.tsx
- src/types.ts
> implement server-contexts

- package-lock.json
- package.json
- src/create-server-context.tsx
- src/get-server-context.tsx
- src/types.ts
> Default value for server contexts

- README.md
- package-lock.json
- package.json
- src/get-page-config.ts
> get-7 implement get-page-config getter

- package/src/get-params.ts
> get-15 fix get-params for optional catch-all routes

- .github/workflows/npm-publish.yml
> get-10 update test step in workflow

- tests/nextjs-app/app/dynamic/force-dynamic/dynamic-force-dynamic.spec.ts
> get-10 fix dynamic-force-dynamic test

- .github/workflows/auto-tests.yml
> get-21 run tests automatically

- package/package-lock.json
- package/package.json
> get-24 release v1.0.0

- examples/isomorphic-context/.gitignore
- examples/isomorphic-context/app/[locale]/page.tsx
- examples/isomorphic-context/app/layout.tsx
- examples/isomorphic-context/app/page.tsx
- examples/isomorphic-context/components/ClientBlock/index.tsx
- examples/isomorphic-context/components/ClientContext/index.tsx
- examples/isomorphic-context/components/ClientContextProvider/index.tsx
- examples/isomorphic-context/components/IsomorphicContextProvider/index.tsx
- examples/isomorphic-context/components/ServerContext/index.tsx
- examples/isomorphic-context/components/ServerContextProvider/index.tsx
- examples/isomorphic-context/components/ServerNav/index.tsx
- examples/isomorphic-context/package.json
- examples/isomorphic-context/tsconfig.json
> get-27 add example with isomorphic provider

- package/package-lock.json
- package/package.json
- package/src/create-server-context.tsx
- package/tsconfig.json
> get-32 server contexts in provider scope

- README.md
- package/package-lock.json
- package/package.json
> get-34 update readme

- .github/workflows/auto-tests.yml
> get-37 fix auto tests

- README.md
- docs/get-search-params.md
- package/package-lock.json
- package/package.json
- package/src/get-search-params.ts
> get-39 deprecate get-search-params method

- README.md
- package/package-lock.json
- package/package.json
> get-41 bump package to 1.3.0

- README.md
- package/package-lock.json
- package/package.json
> get-44 add info about previous name to readme

- eslint.config.mjs
- package.json
- package/src/create-server-context.tsx
- package/src/get-page-config.ts
- package/src/get-params.ts
- package/src/get-pathname.ts
- package/src/get-search-params.ts
- package/src/get-server-context.tsx
- package/src/server-getter-in-client-component-error.ts
- package/src/types.ts
- package/src/utils.ts
- pnpm-lock.yaml
> get-47 format package files

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
> get-48 configure husky

- package/src/get-params.ts
- package/src/utils.ts
- tests/nextjs-app/app/(frontend)/(corporate)/groups/groups.spec.ts
- tests/nextjs-app/app/(frontend)/(corporate)/groups/page.tsx
> get-56 improve groups parsing in get-params

- package.json
- package/package.json
- pnpm-lock.yaml
> get-70 update package deps

- .github/workflows/auto-tests.yml
- tests/base/package.json
- tests/base/tsconfig.json
> get-75 use react canary in tests

- package/src/get-params.ts
- package/src/utils.ts
- tests/base/app/not-found.spec.ts
- tests/base/app/not-found.tsx
- tests/base/app/utils-unit.spec.ts
> get-79 update get-params logic and add new options

- README.md
- package/package.json
- package/src/get-params.ts
- package/src/utils.ts
- tests/base/app/not-found.spec.ts
- tests/base/app/not-found.tsx
- tests/base/app/utils-unit.spec.ts
> get-81 release 1.4.1

- .github/workflows/auto-tests.yml
> get-89 reinstall deps in test workflow

- package/package.json
- pnpm-lock.yaml
> get-94 update dependencies

- README.md
- package.json
> get-97 update documentation link

- package.json
- package/package.json
> get-97 release 2.1.2

- package/src/get-app-params.ts
- package/src/get-app-pathname.ts
- package/src/get-params.ts
- pnpm-lock.yaml
- tests/base/app/not-found.tsx
> get-100 fix page params getter for next 15-4-2-canary
